name: valhallatech_ecommerce
description: Valhalla Tech E-commerce Flutter app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'  # 🔥 Cambio: Más flexible

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  # State Management
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5

  # Networking
  dio: ^5.4.1
  connectivity_plus: ^5.0.2

  # Routing
  go_router: ^14.0.0

  # Dependency Injection
  get_it: ^7.6.7
  injectable: ^2.3.5

  # Storage
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # UI
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  flutter_rating_bar: ^4.0.1
  carousel_slider: ^4.2.1
  pull_to_refresh: ^2.0.0

  # Utils
  intl: ^0.19.0
  logger: ^2.0.2+1
  url_launcher: ^6.2.5
  package_info_plus: ^5.0.1
  uuid: ^4.3.3
  dartz: ^0.10.1
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

  # Code Generation
  build_runner: ^2.4.8
  injectable_generator: ^2.5.0
  json_serializable: ^6.7.1
  freezed: ^2.4.7
  hive_generator: ^2.0.1
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.13

flutter:
  uses-material-design: true

  # 🔥 COMENTADO TEMPORALMENTE - Descomenta cuando tengas los archivos
  # assets:
  #   - assets/images/
  #   - assets/icons/
  #   - assets/fonts/

  # 🔥 COMENTADO TEMPORALMENTE - Descomenta cuando tengas los archivos
  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: assets/fonts/Poppins-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Poppins-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Poppins-Bold.ttf
  #         weight: 700